package Telas;

import Classes_Comuns.Banco;
import Classes_Comuns.Datas_e_Horas;
import Classes_Comuns.Relatorio;
import Conexao.Conexao;
import Pacote1.ContaBancaria;
import Pacote1.*;
import Pacote1.*;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marondo Eh a classe MAIN do sistema Contem todas operacoes basicas do
 * sistema
 */
public class frmExecutavel_Banco extends javax.swing.JFrame {

    /**
     * Creates new form Banco
     *
     */
    public frmExecutavel_Banco() {
        initComponents();
        setLocationRelativeTo(null);
        inicializaCardLayouts();
        menuBaixo(true);
        menuCima();
        preenche_lbls(null, null);

    }
    Banco bc = new Banco();
    Conta_Corrente cc = new Conta_Corrente();
    Conta_Poupaca cp = new Conta_Poupaca();
    Relatorio rel = new Relatorio();
    pTabela pTab = new pTabela();
    Datas_e_Horas dh = new Datas_e_Horas();
    private CardLayout layoutCentral;

    /**
     * Inicializa o painel cardLayout
     *
     */
    private void inicializaCardLayouts() {
        layoutCentral = (CardLayout) pCard_Central.getLayout();

        pCard_Central.add(pHome, "pHome");
        layoutCentral.show(pCard_Central, "pHome");

        pCard_Central.add(pTab, "pTab");
    }
    String txt = "";

    /**
     * Habilita ou desabilita o menu superio do sistem baseando se num valor que
     * eh capturado do botaoFINALIZAR
     *
     */
    private void menuCima() {
        if (txt.equalsIgnoreCase(btnFinalizar.getText())) {
            btnDepo.setEnabled(true);
            btnLevant.setEnabled(true);
            btnTransf.setEnabled(true);
            btnRelatorio.setEnabled(true);
            layoutCentral.show(pCard_Central, "pHome");
        } else {
            btnDepo.setEnabled(false);
            btnLevant.setEnabled(false);
            btnTransf.setEnabled(false);
            btnRelatorio.setEnabled(false);
        }
    }

    /**
     * Habilita ou desabilita o manu de baixo dependendo das cisrcunstancias
     *
     * @param v
     */
    private void menuBaixo(boolean v) {
        btnAddConta.setEnabled(v);
        btnFinalizar.setEnabled(v);
        btnPesq.setEnabled(v);
        btnRemov.setEnabled(v);
        btnListrar.setEnabled(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        pMenu = new javax.swing.JPanel();
        btnDepo = new javax.swing.JButton();
        btnLevant = new javax.swing.JButton();
        btnTransf = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        pCard_Central = new javax.swing.JPanel();
        pHome = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblLogado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pCardAdmin = new javax.swing.JPanel();
        pHomeAdmin = new javax.swing.JPanel();
        pAdmin_CadastrarRemover = new javax.swing.JPanel();
        btnAddConta = new javax.swing.JButton();
        btnPesq = new javax.swing.JButton();
        btnRemov = new javax.swing.JButton();
        btnListrar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblnrCont1 = new javax.swing.JLabel();
        lblnrCont2 = new javax.swing.JLabel();
        lblSaldo1 = new javax.swing.JLabel();
        lblSaldo2 = new javax.swing.JLabel();
        lblHist1 = new javax.swing.JLabel();
        lblHist2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 0, 3));

        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tela_Icons/Very-Basic-Close-iconll.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2lblSairMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tela_Icons/Arrow-Down-3-iconlll.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3lblMinimizarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Swis721 BlkOul BT", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tela_Icons/money-iconlll.png"))); // NOI18N
        jLabel4.setText("DMI-BANK");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9.add(jPanel6);

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setLayout(new java.awt.GridLayout(1, 1));

        pMenu.setLayout(new java.awt.GridLayout(2, 2));

        btnDepo.setBackground(new java.awt.Color(0, 102, 102));
        btnDepo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDepo.setText("DEPOSITAR");
        btnDepo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnDepo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepoActionPerformed(evt);
            }
        });
        pMenu.add(btnDepo);

        btnLevant.setBackground(new java.awt.Color(0, 102, 102));
        btnLevant.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLevant.setText("LEVANTAR");
        btnLevant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnLevant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLevant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantActionPerformed(evt);
            }
        });
        pMenu.add(btnLevant);

        btnTransf.setBackground(new java.awt.Color(0, 102, 102));
        btnTransf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTransf.setText("TRANSFERIR");
        btnTransf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnTransf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransfActionPerformed(evt);
            }
        });
        pMenu.add(btnTransf);

        btnRelatorio.setBackground(new java.awt.Color(0, 102, 102));
        btnRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRelatorio.setText("RELATORIO");
        btnRelatorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        pMenu.add(btnRelatorio);

        jPanel10.add(pMenu);

        jPanel9.add(jPanel10);

        getContentPane().add(jPanel9);

        pCard_Central.setBackground(new java.awt.Color(0, 51, 51));
        pCard_Central.setLayout(new java.awt.CardLayout());

        pHome.setBackground(new java.awt.Color(0, 51, 51));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setOpaque(true);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tela_Icons/Satisfeitos.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tela_Icons/stats-up-icon.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Swis721 BlkOul BT", 1, 43)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SEMPRE");

        jLabel10.setFont(new java.awt.Font("Swis721 BlkOul BT", 1, 43)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AO SEU FAVOR");

        lblLogado.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblLogado.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(lblLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHomeLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pHomeLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pCard_Central.add(pHome, "card2");

        getContentPane().add(pCard_Central);

        pCardAdmin.setBackground(new java.awt.Color(0, 102, 102));

        pHomeAdmin.setBackground(new java.awt.Color(0, 102, 102));
        pHomeAdmin.setLayout(new java.awt.GridLayout(1, 1));

        pAdmin_CadastrarRemover.setBackground(new java.awt.Color(0, 102, 102));
        pAdmin_CadastrarRemover.setLayout(new java.awt.GridLayout(1, 0, 2, 30));

        btnAddConta.setBackground(new java.awt.Color(0, 102, 102));
        btnAddConta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddConta.setText("NOVA CONTA");
        btnAddConta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnAddConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContaActionPerformed(evt);
            }
        });
        pAdmin_CadastrarRemover.add(btnAddConta);

        btnPesq.setBackground(new java.awt.Color(0, 102, 102));
        btnPesq.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPesq.setText("PESQUISAR");
        btnPesq.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnPesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });
        pAdmin_CadastrarRemover.add(btnPesq);

        btnRemov.setBackground(new java.awt.Color(0, 102, 102));
        btnRemov.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRemov.setText("REMOVER");
        btnRemov.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnRemov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovActionPerformed(evt);
            }
        });
        pAdmin_CadastrarRemover.add(btnRemov);

        btnListrar.setBackground(new java.awt.Color(0, 102, 102));
        btnListrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnListrar.setText("LISTAR");
        btnListrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnListrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListrarActionPerformed(evt);
            }
        });
        pAdmin_CadastrarRemover.add(btnListrar);

        btnFinalizar.setBackground(new java.awt.Color(0, 102, 102));
        btnFinalizar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true));
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        pAdmin_CadastrarRemover.add(btnFinalizar);

        pHomeAdmin.add(pAdmin_CadastrarRemover);

        javax.swing.GroupLayout pCardAdminLayout = new javax.swing.GroupLayout(pCardAdmin);
        pCardAdmin.setLayout(pCardAdminLayout);
        pCardAdminLayout.setHorizontalGroup(
            pCardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pHomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pCardAdminLayout.setVerticalGroup(
            pCardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pHomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 3, 5));

        lblnrCont1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnrCont1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel3.add(lblnrCont1);

        lblnrCont2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnrCont2.setForeground(new java.awt.Color(255, 255, 0));
        lblnrCont2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(lblnrCont2);

        lblSaldo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSaldo1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel3.add(lblSaldo1);

        lblSaldo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSaldo2.setForeground(new java.awt.Color(255, 255, 0));
        lblSaldo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(lblSaldo2);

        lblHist1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHist1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel3.add(lblHist1);

        lblHist2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHist2.setForeground(new java.awt.Color(255, 255, 0));
        lblHist2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(lblHist2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(pCardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Botao sair do sistema
     *
     * @param evt
     */
    private void jLabel2lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2lblSairMouseClicked
        if (JOptionPane.showConfirmDialog(null, "          Deseja sair?", "EXIT", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel2lblSairMouseClicked
    /**
     * Botao minmizar
     *
     * @param evt
     */
    private void jLabel3lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3lblMinimizarMouseClicked
        this.setState(frmExecutavel_Banco.ICONIFIED);
    }//GEN-LAST:event_jLabel3lblMinimizarMouseClicked
    /**
     * O usuario confirma se deseja sair ou habilitar o menu superior
     *
     * @param evt
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        preenche_lbls(null, null);
        txt = btnFinalizar.getText();
        try {
            switch (JOptionPane.showInputDialog(""
                    + "1. Sair do Sistema!\n2. Menu"
                    + " de Operacoes!")) {
                case "1": {
                    System.exit(0);
                }
                break;
                case "2": {
                    menuCima();
                    menuBaixo(false);
                }
                break;
                default: {
                    JOptionPane.showMessageDialog(null, "Opcao invalida!");
                }

            }
        } catch (Exception e) {
        }
        txt = "";
    }//GEN-LAST:event_btnFinalizarActionPerformed
    /**
     * Exibe a tabela com todos os registos
     *
     * @param evt
     */
    private void btnListrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListrarActionPerformed
        preenche_lbls(null, null);
        pTab.preenche_a_tbl(bc.getLista_de_Contas());
        layoutCentral.show(pCard_Central, "pTab");
    }//GEN-LAST:event_btnListrarActionPerformed
    /**
     * Exibe tambe todas as contas da lista na tabela
     *
     * @param evt
     */
    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        try {
            switch (JOptionPane.showInputDialog(""
                    + "1. Relatorio de contas!\n"
                    + "2. Voltar ao menu anterior!")) {
                case "1": {
                    //   pTab = new pTabela(bc.getLista_de_Contas());
                    pTab.preenche_a_tbl(bc.getLista_de_Contas());
                    layoutCentral.show(pCard_Central, "pTab");
                }
                break;
                case "2": {
                    menuCima();
                    menuBaixo(true);
                }
                break;
                default: {
                    JOptionPane.showMessageDialog(null, "Opcao invalida!");
                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed
    boolean sim = true;

    /**
     * Executa criar contas
     *
     * @param evt
     */
    private void btnAddContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContaActionPerformed
        try {
            int pos = 100;
            if (bc.getLista_de_Contas() != null) {
                pos += bc.getLista_de_Contas().size();
            }
            String op = JOptionPane.showInputDialog(""
                    + "TIPO DE CONTA\n"
                    + "1. Conta Corrente!\n"
                    + "2. Conta Poupanca!");
            if (op.equals("1")) {
                cc = new Conta_Corrente();
                sim = true;
                do {
                    cc.setNrConta(pos);
                    JOptionPane.showMessageDialog(null, "Nr de conta atribuido: " + pos + "!");
                    do {
                        try {
                            double saldoIn = Double.parseDouble(JOptionPane.showInputDialog("Digite o saldo inicial!"));
                            if (saldoIn > 0) {
                                cc.depositar(saldoIn);
                                sim = false;
                            } else {
                                JOptionPane.showMessageDialog(null, "Deve digitar valor positivo!");
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Erro de digitacao!");
                        }
                    } while (sim);
                    // rel.gerarRelatório(cc);
                    JOptionPane.showMessageDialog(null, "Conta adicionada!");
                    preenche_lbls(cc, null);
                    bc.inserir(cc);
                    pTab.preenche_a_tbl(bc.getLista_de_Contas());
                } while (sim);
            } else if (op.equals("2")) {
                cp = new Conta_Poupaca();
                do {
                    cp.setNrConta(pos);
                    JOptionPane.showMessageDialog(null, "Seu nr de conta eh: " + pos + "!");
                    do {
                        try {
                            double saldoIn = Double.parseDouble(JOptionPane.showInputDialog("Digite o saldo inicial!"));
                            if (saldoIn > 0) {
                                cp.depositar(saldoIn);
                                sim = false;
                            } else {
                                JOptionPane.showMessageDialog(null, "Deve digitar valor positivo!");
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Erro de digitacao!");
                        }
                    } while (sim);
                    //   rel.gerarRelatório(cp);  
                    preenche_lbls(cp, null);
                    bc.inserir(cp);
                    pTab.preenche_a_tbl(bc.getLista_de_Contas());
                    JOptionPane.showMessageDialog(null, "Conta adicionada!");
                } while (sim);
            } else {
                JOptionPane.showMessageDialog(null, "Opcao invalida!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddContaActionPerformed
    /**
     * Exibe dados duma dada conta caso seja encontrada, em labels
     */
    ContaBancaria preenche_lbls(ContaBancaria cont1, ContaBancaria cont2) {
        if (cont1 != null) {
            lblHist1.setText("     Historico: " + cont1.getHistorico());
            lblSaldo1.setText("     Saldo: " + cont1.getSaldo());
            lblnrCont1.setText("     Nr. de conta: " + cont1.getNrConta());
        } else {
            lblHist1.setText("     ---");
            lblSaldo1.setText("     ---");
            lblnrCont1.setText("     ---");
        }
        if (cont2 != null) {
            lblHist2.setText("Historico: " + cont2.getHistorico() + "     ");
            lblSaldo2.setText("Saldo: " + cont2.getSaldo() + "     ");
            lblnrCont2.setText("Nr. de conta: " + cont2.getNrConta() + "     ");
        } else {
            lblHist2.setText("---     ");
            lblSaldo2.setText("---     ");
            lblnrCont2.setText("---     ");
        }
        return cont1;
    }

    /**
     * Pesquisa na lista
     *
     * @param evt
     */
    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        try {
            preenche_lbls(bc.procurarConta(Integer.parseInt(JOptionPane.showInputDialog("Digite o nr da conta:"))), null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de digitacao!\nDigite inteiros.");
        }
    }//GEN-LAST:event_btnPesqActionPerformed
    /**
     * Remos na lista
     *
     * @param evt
     */
    private void btnRemovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovActionPerformed
        try {
            bc.remover(bc.procurarConta(Integer.parseInt(JOptionPane.showInputDialog("Digite o nr da conta:"))));
            pTab.preenche_a_tbl(bc.getLista_de_Contas());
            JOptionPane.showMessageDialog(null, "Conta removida!");
            preenche_lbls(null, null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de digitacao!\nDigite inteiros.");
        }
    }//GEN-LAST:event_btnRemovActionPerformed
    /**
     * Deposita numa conta especificada
     *
     * @param evt
     */
    private void btnDepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepoActionPerformed
        try {
            ContaBancaria c = preenche_lbls(bc.procurarConta(Integer.parseInt(JOptionPane.showInputDialog("Digite o nr da conta:"))), null);
            int i = 0;
            for (ContaBancaria ob : bc.getLista_de_Contas()) {
                if (ob.getNrConta() == c.getNrConta()) {
                    c.depositar(Double.parseDouble(JOptionPane.showInputDialog("Digite o valor a depositar!")));
                    bc.lista_de_Contas.set(i, c);
                    con.cmd_Salva_Conta_Actualizado(bc.caminho, bc.lista_de_Contas);

                    pTab.preenche_a_tbl(bc.getLista_de_Contas());
                    preenche_lbls(c, null);
                    break;
                }
                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de digitacao!\nDigite inteiros.");
        }
    }//GEN-LAST:event_btnDepoActionPerformed
    /**
     * Levanta um valor de uma dada conata
     *
     * @param evt
     */
    private void btnLevantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantActionPerformed
        try {
            ContaBancaria c = preenche_lbls(bc.procurarConta(Integer.parseInt(JOptionPane.showInputDialog("Digite o nr da conta:"))), null);
            int i = 0;
            if (c != null) {
                for (ContaBancaria ob : bc.getLista_de_Contas()) {
                    if (ob.getNrConta() == c.getNrConta()) {
                        if (c.sacar(Double.parseDouble(JOptionPane.showInputDialog("Digite o valor a levantar!"))) == 1) {
                            bc.lista_de_Contas.set(i, c);
                            con.cmd_Salva_Conta_Actualizado(bc.caminho, bc.lista_de_Contas);
                            pTab.preenche_a_tbl(bc.getLista_de_Contas());
                            JOptionPane.showMessageDialog(null, "Levantado com sucesso!");
                        }
                        preenche_lbls(c, null);
                        break;
                    }
                    i++;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de digitacao!\nDigite inteiros.");
        }
    }//GEN-LAST:event_btnLevantActionPerformed
    /**
     * Faz a transferencia entre duas contas informadas
     *
     * @param evt
     */
    Conexao con = new Conexao();
    private void btnTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransfActionPerformed
        try {
            ContaBancaria origem = preenche_lbls(bc.procurarConta(Integer.parseInt(JOptionPane.showInputDialog("Digite o nr da conta - origem:"))), null);
            ContaBancaria destino = bc.procurarConta(Integer.parseInt(JOptionPane.showInputDialog("Digite o nr da conta - destino:")));
            preenche_lbls(origem, destino);
            int or = 0;
            if (origem != null && destino != null) {
                if (origem != destino) {
                    for (ContaBancaria inicio : bc.lista_de_Contas) {
                        if (inicio.getNrConta() == origem.getNrConta()) {
                            int d = 0;
                            for (ContaBancaria fim : bc.lista_de_Contas) {
                                if (fim.getNrConta() == destino.getNrConta()) {
                                    double valor = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor a transferir!"));

                                    origem.transferir(valor, destino);
                                    bc.lista_de_Contas.set(or, origem);
                                    bc.lista_de_Contas.set(d, fim);
                                    con.cmd_Salva_Conta_Actualizado(bc.caminho, bc.lista_de_Contas);
                                    pTab.preenche_a_tbl(bc.getLista_de_Contas());
                                    preenche_lbls(origem, destino);
                                    break;
                                }
                                d++;
                            }
                            break;
                        } else {
                            JOptionPane.showMessageDialog(null, "inicio == origem." + inicio.getNrConta() + "" + origem.getNrConta());
                        }
                        or++;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Erro! Devem ser contas diferentes.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro de digitacao!\nDigite inteiros.");
        }
    }//GEN-LAST:event_btnTransfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExecutavel_Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExecutavel_Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExecutavel_Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExecutavel_Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmExecutavel_Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddConta;
    private javax.swing.JButton btnDepo;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnLevant;
    private javax.swing.JButton btnListrar;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnRemov;
    private javax.swing.JButton btnTransf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblHist1;
    private javax.swing.JLabel lblHist2;
    private javax.swing.JLabel lblLogado;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldo2;
    private javax.swing.JLabel lblnrCont1;
    private javax.swing.JLabel lblnrCont2;
    private javax.swing.JPanel pAdmin_CadastrarRemover;
    private javax.swing.JPanel pCardAdmin;
    private javax.swing.JPanel pCard_Central;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pHomeAdmin;
    private javax.swing.JPanel pMenu;
    // End of variables declaration//GEN-END:variables
}
